version: '3.8'
services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
      - redis
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
  mariadb:
    image: mariadb:10.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: admin_casadecambio
      MYSQL_USER: admin_casadecambio
      MYSQL_PASSWORD: ctfEDagmR3*!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  db_data: 